name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
         - ubuntu-latest
         - windows-latest
         - macos-latest
        node:
          - 18
          - 20
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          # Cache key uses the contents of `package-lock.json` to identify unique cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
          path: |
            node_modules
      
      - run: npm ci
      
      - run: npm test
